//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Service.IntegrationApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDD
    {
        public int ITid { get; set; }
        public int ADDid { get; set; }
        public string Name { get; set; }
        public Nullable<double> PDKMPRoom { get; set; }
        public Nullable<double> PDKMPAir { get; set; }
        public Nullable<double> PDKCCRoom { get; set; }
        public Nullable<double> PDKCCAir { get; set; }
    }
}
