//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Service.IntegrationApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTT_SET
    {
        public int CPid { get; set; }
        public int Ndev { get; set; }
        public Nullable<double> Level { get; set; }
        public Nullable<double> Factor { get; set; }
    
        public virtual CP CP { get; set; }
    }
}
