//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Service.IntegrationApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAR()
        {
            this.DC = new HashSet<DC>();
            this.V_ALARM = new HashSet<V_ALARM>();
            this.WS = new HashSet<WS>();
            this.RepDev = new HashSet<RepDev>();
        }
    
        public int PARid { get; set; }
        public Nullable<int> ITid { get; set; }
        public Nullable<int> DIMid { get; set; }
        public Nullable<int> BDid { get; set; }
        public Nullable<int> Alg { get; set; }
        public Nullable<int> SubAlg { get; set; }
        public string TabName { get; set; }
        public string TabField { get; set; }
        public string Name { get; set; }
        public Nullable<int> CRITid { get; set; }
        public Nullable<int> FORMATid { get; set; }
        public Nullable<int> OnWriteDB { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> Offset { get; set; }
        public Nullable<int> Len { get; set; }
        public Nullable<int> TYPEid { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> DTid { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> DTtel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DC> DC { get; set; }
        public virtual DIM DIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_ALARM> V_ALARM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WS> WS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepDev> RepDev { get; set; }
    }
}
