//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Service.IntegrationApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLevelSql
    {
        public int ID_LEVEL { get; set; }
        public Nullable<int> LevelNum { get; set; }
        public string SqlLevel { get; set; }
        public Nullable<short> ReadOnly { get; set; }
    }
}
