//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Service.IntegrationApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ALARM
    {
        public int MSid { get; set; }
        public int PARid { get; set; }
        public Nullable<int> MSGid { get; set; }
        public Nullable<int> ACKid { get; set; }
    
        public virtual PAR PAR { get; set; }
        public virtual V_MS V_MS { get; set; }
    }
}
