//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Service.IntegrationApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SENSIS_NH3
    {
        public int V_SENSIS_NH3id { get; set; }
        public Nullable<int> MSid { get; set; }
        public Nullable<double> P0036 { get; set; }
        public Nullable<int> P1036 { get; set; }
        public Nullable<int> P6336 { get; set; }
    
        public virtual V_MS V_MS { get; set; }
    }
}
