//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Service.IntegrationApp.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WS
    {
        public int PARid { get; set; }
        public int Bit { get; set; }
        public Nullable<int> CONDid { get; set; }
        public string Text { get; set; }
    
        public virtual PAR PAR { get; set; }
    }
}
