//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALG
    {
        public int Alg1 { get; set; }
        public int SubAlg { get; set; }
        public int Value { get; set; }
        public Nullable<int> CONDid { get; set; }
        public string Text { get; set; }
        public Nullable<int> MSGid { get; set; }
        public byte[] MSb { get; set; }
    }
}
