//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOUNDS
    {
        public int CPid { get; set; }
        public int Ndev { get; set; }
        public int PARid { get; set; }
        public Nullable<double> NRG { get; set; }
        public Nullable<double> VRG { get; set; }
        public Nullable<double> NAG { get; set; }
        public Nullable<double> VAG { get; set; }
        public Nullable<double> NVG { get; set; }
        public Nullable<double> VVG { get; set; }
        public Nullable<double> NIG { get; set; }
        public Nullable<double> PDKmp { get; set; }
        public Nullable<double> PDKcc { get; set; }
    }
}
