//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_MS()
        {
            this.C_SENSIS_CL2_D = new HashSet<C_SENSIS_CL2_D>();
            this.C_SENSIS_CL2_DD = new HashSet<C_SENSIS_CL2_DD>();
            this.C_SENSIS_CL2_M = new HashSet<C_SENSIS_CL2_M>();
            this.C_SENSIS_CL2_MM = new HashSet<C_SENSIS_CL2_MM>();
            this.C_SENSIS_CL2_Y = new HashSet<C_SENSIS_CL2_Y>();
            this.C_SENSIS_CL2_YY = new HashSet<C_SENSIS_CL2_YY>();
            this.C_SENSIS_CO_D = new HashSet<C_SENSIS_CO_D>();
            this.C_SENSIS_CO_DD = new HashSet<C_SENSIS_CO_DD>();
            this.C_SENSIS_CO_M = new HashSet<C_SENSIS_CO_M>();
            this.C_SENSIS_CO_MM = new HashSet<C_SENSIS_CO_MM>();
            this.C_SENSIS_CO_Y = new HashSet<C_SENSIS_CO_Y>();
            this.C_SENSIS_CO_YY = new HashSet<C_SENSIS_CO_YY>();
            this.C_SENSIS_CXHY_D = new HashSet<C_SENSIS_CXHY_D>();
            this.C_SENSIS_CXHY_DD = new HashSet<C_SENSIS_CXHY_DD>();
            this.C_SENSIS_CXHY_M = new HashSet<C_SENSIS_CXHY_M>();
            this.C_SENSIS_CXHY_MM = new HashSet<C_SENSIS_CXHY_MM>();
            this.C_SENSIS_CXHY_Y = new HashSet<C_SENSIS_CXHY_Y>();
            this.C_SENSIS_CXHY_YY = new HashSet<C_SENSIS_CXHY_YY>();
            this.C_SENSIS_HCL_D = new HashSet<C_SENSIS_HCL_D>();
            this.C_SENSIS_HCL_DD = new HashSet<C_SENSIS_HCL_DD>();
            this.C_SENSIS_HCL_M = new HashSet<C_SENSIS_HCL_M>();
            this.C_SENSIS_HCL_MM = new HashSet<C_SENSIS_HCL_MM>();
            this.C_SENSIS_HCL_Y = new HashSet<C_SENSIS_HCL_Y>();
            this.C_SENSIS_HCL_YY = new HashSet<C_SENSIS_HCL_YY>();
            this.C_SENSIS_HCOH_D = new HashSet<C_SENSIS_HCOH_D>();
            this.C_SENSIS_HCOH_DD = new HashSet<C_SENSIS_HCOH_DD>();
            this.C_SENSIS_HCOH_M = new HashSet<C_SENSIS_HCOH_M>();
            this.C_SENSIS_HCOH_MM = new HashSet<C_SENSIS_HCOH_MM>();
            this.C_SENSIS_HCOH_Y = new HashSet<C_SENSIS_HCOH_Y>();
            this.C_SENSIS_HCOH_YY = new HashSet<C_SENSIS_HCOH_YY>();
            this.C_SENSIS_HF_D = new HashSet<C_SENSIS_HF_D>();
            this.C_SENSIS_HF_DD = new HashSet<C_SENSIS_HF_DD>();
            this.C_SENSIS_HF_M = new HashSet<C_SENSIS_HF_M>();
            this.C_SENSIS_HF_MM = new HashSet<C_SENSIS_HF_MM>();
            this.C_SENSIS_HF_Y = new HashSet<C_SENSIS_HF_Y>();
            this.C_SENSIS_HF_YY = new HashSet<C_SENSIS_HF_YY>();
            this.C_SENSIS_NO2_D = new HashSet<C_SENSIS_NO2_D>();
            this.C_SENSIS_NO2_DD = new HashSet<C_SENSIS_NO2_DD>();
            this.C_SENSIS_NO2_M = new HashSet<C_SENSIS_NO2_M>();
            this.C_SENSIS_NO2_MM = new HashSet<C_SENSIS_NO2_MM>();
            this.C_SENSIS_NO2_Y = new HashSet<C_SENSIS_NO2_Y>();
            this.C_SENSIS_NO2_YY = new HashSet<C_SENSIS_NO2_YY>();
            this.C_SENSIS_SO2_D = new HashSet<C_SENSIS_SO2_D>();
            this.C_SENSIS_SO2_DD = new HashSet<C_SENSIS_SO2_DD>();
            this.C_SENSIS_SO2_M = new HashSet<C_SENSIS_SO2_M>();
            this.C_SENSIS_SO2_MM = new HashSet<C_SENSIS_SO2_MM>();
            this.C_SENSIS_SO2_Y = new HashSet<C_SENSIS_SO2_Y>();
            this.C_SENSIS_SO2_YY = new HashSet<C_SENSIS_SO2_YY>();
        }
    
        public int MSid { get; set; }
        public System.DateTime MTime { get; set; }
        public System.DateTime CTime { get; set; }
        public int CPid { get; set; }
        public int ITid { get; set; }
        public int Ndev { get; set; }
        public int Parid { get; set; }
        public int ITVid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_CL2_D> C_SENSIS_CL2_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_CL2_DD> C_SENSIS_CL2_DD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_CL2_M> C_SENSIS_CL2_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_CL2_MM> C_SENSIS_CL2_MM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_CL2_Y> C_SENSIS_CL2_Y { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_CL2_YY> C_SENSIS_CL2_YY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_CO_D> C_SENSIS_CO_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_CO_DD> C_SENSIS_CO_DD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_CO_M> C_SENSIS_CO_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_CO_MM> C_SENSIS_CO_MM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_CO_Y> C_SENSIS_CO_Y { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_CO_YY> C_SENSIS_CO_YY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_CXHY_D> C_SENSIS_CXHY_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_CXHY_DD> C_SENSIS_CXHY_DD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_CXHY_M> C_SENSIS_CXHY_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_CXHY_MM> C_SENSIS_CXHY_MM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_CXHY_Y> C_SENSIS_CXHY_Y { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_CXHY_YY> C_SENSIS_CXHY_YY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_HCL_D> C_SENSIS_HCL_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_HCL_DD> C_SENSIS_HCL_DD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_HCL_M> C_SENSIS_HCL_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_HCL_MM> C_SENSIS_HCL_MM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_HCL_Y> C_SENSIS_HCL_Y { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_HCL_YY> C_SENSIS_HCL_YY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_HCOH_D> C_SENSIS_HCOH_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_HCOH_DD> C_SENSIS_HCOH_DD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_HCOH_M> C_SENSIS_HCOH_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_HCOH_MM> C_SENSIS_HCOH_MM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_HCOH_Y> C_SENSIS_HCOH_Y { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_HCOH_YY> C_SENSIS_HCOH_YY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_HF_D> C_SENSIS_HF_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_HF_DD> C_SENSIS_HF_DD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_HF_M> C_SENSIS_HF_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_HF_MM> C_SENSIS_HF_MM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_HF_Y> C_SENSIS_HF_Y { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_HF_YY> C_SENSIS_HF_YY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_NO2_D> C_SENSIS_NO2_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_NO2_DD> C_SENSIS_NO2_DD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_NO2_M> C_SENSIS_NO2_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_NO2_MM> C_SENSIS_NO2_MM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_NO2_Y> C_SENSIS_NO2_Y { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_NO2_YY> C_SENSIS_NO2_YY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_SO2_D> C_SENSIS_SO2_D { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_SO2_DD> C_SENSIS_SO2_DD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_SO2_M> C_SENSIS_SO2_M { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_SO2_MM> C_SENSIS_SO2_MM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_SO2_Y> C_SENSIS_SO2_Y { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_SENSIS_SO2_YY> C_SENSIS_SO2_YY { get; set; }
    }
}
