//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CP()
        {
            this.DEV = new HashSet<DEV>();
            this.OTT_SET = new HashSet<OTT_SET>();
            this.GROUP_CP = new HashSet<GROUP_CP>();
        }
    
        public int CPid { get; set; }
        public string Name { get; set; }
        public Nullable<int> FPSid { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> ON { get; set; }
        public string ShortName { get; set; }
        public Nullable<double> Longi { get; set; }
        public Nullable<double> Lati { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEV> DEV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OTT_SET> OTT_SET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUP_CP> GROUP_CP { get; set; }
    }
}
