//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSG
    {
        public int MSGid { get; set; }
        public string Msgtext { get; set; }
        public Nullable<int> CONDid { get; set; }
        public Nullable<int> ACK { get; set; }
    }
}
