//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERS
    {
        public int USERid { get; set; }
        public string Name { get; set; }
        public string Passwd { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ON { get; set; }
    }
}
