//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepDev
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RepDev()
        {
            this.GROUP_CP = new HashSet<GROUP_CP>();
        }
    
        public int IDRD { get; set; }
        public int PARid { get; set; }
        public int Number { get; set; }
        public Nullable<int> Calc { get; set; }
    
        public virtual DEV DEV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUP_CP> GROUP_CP { get; set; }
        public virtual PAR PAR { get; set; }
    }
}
