//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRepColumns
    {
        public int ID_Col { get; set; }
        public Nullable<int> IDRep { get; set; }
        public Nullable<int> PARid { get; set; }
        public Nullable<int> ColNum { get; set; }
        public Nullable<int> ColWidth { get; set; }
        public string Name { get; set; }
        public string ParDim { get; set; }
        public string TabName { get; set; }
        public string TabField { get; set; }
        public Nullable<long> CPid { get; set; }
        public Nullable<int> NDev { get; set; }
        public string TabFieldStat { get; set; }
        public Nullable<long> ITid { get; set; }
        public Nullable<short> IsChart { get; set; }
        public Nullable<int> ColorChatr { get; set; }
    
        public virtual TRepList TRepList { get; set; }
    }
}
