//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUserPassword
    {
        public int UserNumber { get; set; }
        public string UserNume { get; set; }
        public string Password { get; set; }
        public string PathName { get; set; }
        public string PathDataFiles { get; set; }
    }
}
