//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GT
    {
        public int V_GTid { get; set; }
        public Nullable<int> MSid { get; set; }
        public Nullable<double> P0111 { get; set; }
        public Nullable<int> P1111 { get; set; }
        public Nullable<double> P0212 { get; set; }
        public Nullable<int> P1212 { get; set; }
        public Nullable<int> P0400 { get; set; }
        public Nullable<int> P0401 { get; set; }
        public Nullable<int> P0402 { get; set; }
        public Nullable<int> P0408 { get; set; }
        public Nullable<double> P0409 { get; set; }
    
        public virtual V_MS V_MS { get; set; }
    }
}
