//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_MS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public V_MS()
        {
            this.V_ALARM = new HashSet<V_ALARM>();
            this.V_EPC = new HashSet<V_EPC>();
            this.V_GPS = new HashSet<V_GPS>();
            this.V_GT = new HashSet<V_GT>();
            this.V_MGT = new HashSet<V_MGT>();
            this.V_OTT = new HashSet<V_OTT>();
            this.V_POLY_CL2 = new HashSet<V_POLY_CL2>();
            this.V_POLY_CO = new HashSet<V_POLY_CO>();
            this.V_POLY_HCL = new HashSet<V_POLY_HCL>();
            this.V_POLY_HF = new HashSet<V_POLY_HF>();
            this.V_POLY_NH3 = new HashSet<V_POLY_NH3>();
            this.V_POLY_NO2 = new HashSet<V_POLY_NO2>();
            this.V_POLY_SO2 = new HashSet<V_POLY_SO2>();
            this.V_POLY = new HashSet<V_POLY>();
            this.V_REGARD_CL2 = new HashSet<V_REGARD_CL2>();
            this.V_REGARD = new HashSet<V_REGARD>();
            this.V_SENSIS_CL2 = new HashSet<V_SENSIS_CL2>();
            this.V_SENSIS_CO = new HashSet<V_SENSIS_CO>();
            this.V_SENSIS_CXHY = new HashSet<V_SENSIS_CXHY>();
            this.V_SENSIS_HCL = new HashSet<V_SENSIS_HCL>();
            this.V_SENSIS_HCOH = new HashSet<V_SENSIS_HCOH>();
            this.V_SENSIS_HF = new HashSet<V_SENSIS_HF>();
            this.V_SENSIS_NH3 = new HashSet<V_SENSIS_NH3>();
            this.V_SENSIS_NO = new HashSet<V_SENSIS_NO>();
            this.V_SENSIS_NO2 = new HashSet<V_SENSIS_NO2>();
            this.V_SENSIS_SO2 = new HashSet<V_SENSIS_SO2>();
            this.V_SENSIS = new HashSet<V_SENSIS>();
            this.V_STAT = new HashSet<V_STAT>();
            this.V_UTP = new HashSet<V_UTP>();
            this.V_WXT = new HashSet<V_WXT>();
            this.V_SSD = new HashSet<V_SSD>();
        }
    
        public int MSid { get; set; }
        public Nullable<System.DateTime> MTime { get; set; }
        public Nullable<System.DateTime> CTime { get; set; }
        public Nullable<int> MIid { get; set; }
        public Nullable<int> CPid { get; set; }
        public Nullable<int> Ndev { get; set; }
        public int ITid { get; set; }
        public Nullable<int> PCycle { get; set; }
        public Nullable<int> REGid { get; set; }
        public Nullable<int> GMSid { get; set; }
        public byte[] GMSb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_ALARM> V_ALARM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_EPC> V_EPC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_GPS> V_GPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_GT> V_GT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_MGT> V_MGT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_OTT> V_OTT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_POLY_CL2> V_POLY_CL2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_POLY_CO> V_POLY_CO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_POLY_HCL> V_POLY_HCL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_POLY_HF> V_POLY_HF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_POLY_NH3> V_POLY_NH3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_POLY_NO2> V_POLY_NO2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_POLY_SO2> V_POLY_SO2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_POLY> V_POLY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_REGARD_CL2> V_REGARD_CL2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_REGARD> V_REGARD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_SENSIS_CL2> V_SENSIS_CL2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_SENSIS_CO> V_SENSIS_CO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_SENSIS_CXHY> V_SENSIS_CXHY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_SENSIS_HCL> V_SENSIS_HCL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_SENSIS_HCOH> V_SENSIS_HCOH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_SENSIS_HF> V_SENSIS_HF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_SENSIS_NH3> V_SENSIS_NH3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_SENSIS_NO> V_SENSIS_NO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_SENSIS_NO2> V_SENSIS_NO2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_SENSIS_SO2> V_SENSIS_SO2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_SENSIS> V_SENSIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_STAT> V_STAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_UTP> V_UTP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_WXT> V_WXT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<V_SSD> V_SSD { get; set; }
    }
}
