//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_OPERS
    {
        public int USERid { get; set; }
        public int ACTIONid { get; set; }
        public Nullable<int> MSid { get; set; }
        public Nullable<int> PARid { get; set; }
        public string Comment { get; set; }
        public System.DateTime aTime { get; set; }
    
        public virtual OPERS OPERS { get; set; }
        public virtual OPERS_ACTION OPERS_ACTION { get; set; }
    }
}
