//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_UTP
    {
        public int V_UTPid { get; set; }
        public Nullable<int> MSid { get; set; }
        public Nullable<int> P0600 { get; set; }
        public Nullable<int> P0601 { get; set; }
        public string P0602 { get; set; }
        public Nullable<int> P0603 { get; set; }
        public Nullable<int> P0608 { get; set; }
        public Nullable<double> P0609 { get; set; }
    
        public virtual V_MS V_MS { get; set; }
    }
}
