//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dissertation.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WXT
    {
        public int V_WXTid { get; set; }
        public Nullable<int> MSid { get; set; }
        public Nullable<double> P0173 { get; set; }
        public Nullable<double> P0174 { get; set; }
        public Nullable<double> P0175 { get; set; }
        public Nullable<double> P0176 { get; set; }
        public Nullable<double> P0202 { get; set; }
        public Nullable<double> P0204 { get; set; }
        public Nullable<double> P0205 { get; set; }
        public Nullable<int> P0520 { get; set; }
        public Nullable<int> P0521 { get; set; }
        public Nullable<int> P0530 { get; set; }
        public Nullable<int> P0531 { get; set; }
        public Nullable<int> P0532 { get; set; }
        public Nullable<int> P0533 { get; set; }
        public Nullable<int> P1173 { get; set; }
        public Nullable<int> P1174 { get; set; }
        public Nullable<int> P1175 { get; set; }
        public Nullable<int> P1176 { get; set; }
        public Nullable<int> P1202 { get; set; }
        public Nullable<int> P1204 { get; set; }
        public Nullable<int> P1205 { get; set; }
    
        public virtual V_MS V_MS { get; set; }
    }
}
